workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.linea.ProLinea
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix iOS Deployment Target
        script: |
          cd ios
          echo "platform :ios, '15.0'" > Podfile.new
          cat Podfile | grep -v "^platform :ios" >> Podfile.new
          mv Podfile.new Podfile
          cd ..

      - name: Setup rive_native
        script: |
          cd $CM_BUILD_DIR
          dart run rive_native:setup --platform ios
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.linea.ProLinea \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build iOS App
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa