workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix iOS Deployment Target
        script: |
          cd ios
          # Crear un nuevo Podfile con la plataforma correcta
          cat Podfile | awk 'BEGIN{found=0} /^platform :ios/{if(!found){print "platform :ios, '\''15.0'\''"; found=1} next} 1' > Podfile.tmp && mv Podfile.tmp Podfile
          cd ..
      
      - name: Build iOS App
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa