workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: pe.linea.lineaempresa
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix iOS Deployment Target
        script: |
          cd ios
          echo "platform :ios, '15.0'" > Podfile.new
          cat Podfile | grep -v "^platform :ios" >> Podfile.new
          mv Podfile.new Podfile
          cd ..

      - name: Setup rive_native
        script: |
          cd $CM_BUILD_DIR
          dart run rive_native:setup --platform ios
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files pe.linea.lineaempresa \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build iOS App
        script: |
          cat > /tmp/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>pe.linea.lineaempresa</key>
              <string>CodeMagic</string>
            </dict>
          </dict>
          </plist>
          EOF
          flutter build ipa --release --export-options-plist=/tmp/ExportOptions.plist

      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --testflight
    
    artifacts:
      - build/ios/ipa/*.ipa