workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Set iOS Deployment Target
        script: |
          cd ios
          # Verificar si la línea ya existe y modificarla, o agregarla
          if grep -q "platform :ios" Podfile; then
            sed -i '' 's/platform :ios, .*/platform :ios, '"'"'15.0'"'"'/' Podfile
          else
            # Si no existe, agregarla al inicio del archivo
            (echo "platform :ios, '15.0'"; cat Podfile) > Podfile.tmp && mv Podfile.tmp Podfile
          fi
          cd ..
      
      - name: Build iOS App
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa