workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix iOS Deployment Target
        script: |
          cd ios
          echo "platform :ios, '15.0'" > Podfile.new
          cat Podfile | grep -v "^platform :ios" >> Podfile.new
          mv Podfile.new Podfile
          cd ..
      
      - name: Build iOS App for Simulator
        script: flutter build ios --simulator 
    
    artifacts:
      - build/ios/Release-iphonesimulator/*.app