workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix iOS Deployment Target
        script: |
          ruby -i -pe "gsub(/platform :ios, '[^']*'/, \"platform :ios, '15.0'\"); gsub(/^# platform/, \"platform :ios, '15.0'\\n# platform\")" ios/Podfile
      
      - name: Build iOS App
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa