// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFeCK-eBhB6WMQAxgrCUhHA-jixTMjjM8',
    appId: '1:829412782255:web:67bcc280dd8753865a245a',
    messagingSenderId: '829412782255',
    projectId: 'prolinea-c54d2',
    authDomain: 'prolinea-c54d2.firebaseapp.com',
    storageBucket: 'prolinea-c54d2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV6j0-G0DsFUNohkCp5ZFDIyzhqI2jPEc',
    appId: '1:829412782255:ios:41f489e13dc8458c5a245a',
    messagingSenderId: '829412782255',
    projectId: 'prolinea-c54d2',
    storageBucket: 'prolinea-c54d2.appspot.com',
    iosBundleId: 'com.linea.ProLinea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFeCK-eBhB6WMQAxgrCUhHA-jixTMjjM8',
    appId: '1:829412782255:web:818deecb6712a4885a245a',
    messagingSenderId: '829412782255',
    projectId: 'prolinea-c54d2',
    authDomain: 'prolinea-c54d2.firebaseapp.com',
    storageBucket: 'prolinea-c54d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV6j0-G0DsFUNohkCp5ZFDIyzhqI2jPEc',
    appId: '1:829412782255:ios:32887c929ac80c0b5a245a',
    messagingSenderId: '829412782255',
    projectId: 'prolinea-c54d2',
    storageBucket: 'prolinea-c54d2.appspot.com',
    iosBundleId: 'pe.linea.lineaempresa',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqE7oEO0c3rgCIbfEi1bBQZWw-z-Bky_I',
    appId: '1:829412782255:android:04ccb57ea1d21aa65a245a',
    messagingSenderId: '829412782255',
    projectId: 'prolinea-c54d2',
    storageBucket: 'prolinea-c54d2.appspot.com',
  );
}
